### ISSUE TITLE
Sample file throws exception

### ISSUE THREAD

**Issue by gkostov** [agnat/node_dbus#1]
Running the example test.js throws this:

```
throw new Error("'path' or 'abstract' attribute required");
      ^
```

Error: 'path' or 'abstract' attribute required
    at new UnixDomainSocket (~/Downloads/agnat-node_dbus-c62dd60/lib/transport.js:37:11)
    at Object.create (~/Downloads/agnat-node_dbus-c62dd60/lib/transport.js:68:28)
    at ~/Downloads/agnat-node_dbus-c62dd60/lib/connection.js:17:32
    at ChildProcess.<anonymous> (~/Downloads/agnat-node_dbus-c62dd60/lib/dbus.js:23:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

I guess the code is still in early development but thought to ask in case it's something that I got wrong and there is a chance to make this module work.

**Comment by agnat** [comment]
Consider this abandon-ware. If I pick up on dbus for node again, then it will probably be [node_libdbus](http://github.com/agnat/node_libdbus), which is not fit for production either.
